### ISSUE TITLE
[Bug]: Wrong message "Failed to get yarn version" for invalid package.json file

### ISSUE THREAD

**Issue by christian-schwaderer** [AikidoSec/safe-chain#135]
### Bug Description

When the `package.json` file is not well-formed JSON, the error I usually get is `Invalid package.json in package.json`. However, with safe-chain, the error suddenly turns into `Error executing command: Failed to get yarn version` - which is misleading

### Steps to Reproduce

2. Change `package.json` file to `foo` 
3. With safe-chain enabled run `yarn` (tested with Yarn 4.10)

### Environment

- Node 22.21.0
- Yarn 4.10.3
- safe-chain 1.1.7

### Error Logs

```shell

```

**Comment by bitterpanda63** [comment]
Hi there, we were able to reproduce and fix the issue, will ping when its released!

**Comment by SanderDeclerck** [comment]
@christian-schwaderer We have released version 1.1.8 of safe-chain. This bug was fixed in that release.

Feel free to comment or reopen if you have any remarks about this.

**Comment by whorvath2** [comment]
FWIW, I think that either this issue still exists, or you've got a regression.
